# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20190401_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.TextField(blank=True, default='bio', max_length=200, null=True),
        ),
    ]
